name: Jenkins Build on Merged PR
on:
  pull_request:
    types: [ closed ]
    branches:
      - production

jobs:
  trigger-jenkins-build:
    name: Jenkins Build
    runs-on: ubuntu-latest
    steps:
      - name: trigger jenkins build url
        run:
          curl https://preview-55cc2cc7-a3b5-47e3-a3b0-6bcaed12a2d0.usergeneratedcontent.udemylabs.com/job/maven-deployment/build?token=${{ secrets.JENKINS_TOKEN }}